# Hospital Serice [Must be NodePort to exposed only for inner container]
apiVersion: v1
kind: Service
metadata:
  name: hospital-service
spec:
  selector:
    app: hospital
  ports:
  - protocol: TCP
    port: 5835
    targetPort: 5835
    nodePort: 31110
  type: NodePort

# Hospital Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital
  template:
    metadata:
      labels:
        app: hospital
    spec:
      containers:
      - name: hospital-container
        # Place the hospital docker image here
        image: sanjeev24bhatt/hospital-microservice:0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5835
        # env-name is used to access env-value in project to call other servies [DNS NAME (must be same as service name)]
